version: '3.8'
services:
  db:
    image: docker.io/postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${HASTL_DB_USER}
      - POSTGRES_PASSWORD=${HASTL_DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
