name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.6.4'
        cabal-version: '3.6'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install base dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -y libsndfile-dev libsdl2-dev libgirepository1.0-dev libwebkit2gtk-4.0-dev libgtksourceview-3.0-dev libadwaita-1-dev
    - name: Install cabal dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks exe:audiocate
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks exe:audiocate
    - name: Run tests
      run: cabal test all
